pre_run_hook: []

jupyter_port: 10801
outer_project_port: 5000
inner_project_port: 5000

project_name: knot
project_verison: 0.1

mounted_repos: [dbconnect,]
mapped_ports:
  8080: 80

prod_mount: True

entry_command: nohup jupyter lab --ip=0.0.0.0 --port=5010 --no-browser --allow-root > /app/logs/jupyter.log 2>&1
# python app.py

environment: auto
